name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ml-artifacts
          path: |
            model_*.pth
            test_samples/
            test_samples/rotation_test/
            test_samples/perturbation_test/
